/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guardatupassword;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Horizon
 */
public class Interfaz extends javax.swing.JFrame {

    private final JOptionPane men = new JOptionPane();
    private Timer animar;
    private ActionListener ejecutarAnimacion;

    private CifrarPassword cifrar;
    //Gestores para el manejo de las tablas
    private GestorUsuario gestorUsuario;
    private Usuarios usuario;
    private GestorClaves gestorClaves;
    private Misclaves misclaves;

    private boolean isSesion = false;//****************************CAMBIAR A FALSE********************

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.jTabla_info.getTableHeader().setReorderingAllowed(false); //Impide mover las columnas en jTable
        this.jPanel_nuevaClaves.setVisible(false);
        this.jPanel_listado.setVisible(false);
        this.jPanel_modifica_pass.setVisible(false);

        this.ejecutarAnimacion = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jButton_nuevaClave.getY() < 368) {
                    jButton_nuevaClave.setLocation(240, jButton_nuevaClave.getY() + 4);
                    jButton_borrar_campos.setLocation(445, jButton_borrar_campos.getY() + 4);
                } else {
                    animar.stop();
                }
            }
        };
       
        //Inicializacion del gestor de Usuario
        this.gestorUsuario = new GestorUsuario();
        this.usuario = gestorUsuario.getUsuarios();
        //Inicializacion del gestor de Claves
        this.gestorClaves = new GestorClaves();
        
        //Inicializacion objeto de cifrado
        this.cifrar= new CifrarPassword();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_sesion = new javax.swing.JFrame();
        jPanel_head_sesion = new javax.swing.JPanel();
        jBoton_sesion_exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel_body_sesion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPassword_sesion = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jBoton_aceptar_sesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_usuario_registro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField_registro = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField_confirmar = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jBoton_registro = new javax.swing.JButton();
        jPanel_head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_Minimizar = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        jPanel_sesion = new javax.swing.JPanel();
        jLabel_usuario = new javax.swing.JLabel();
        Boton_Sesion = new javax.swing.JButton();
        jPanel_menu = new javax.swing.JPanel();
        jBoton_nueva_passw = new javax.swing.JButton();
        jBoton_listar_passw = new javax.swing.JButton();
        jBoton_cambiar_passw = new javax.swing.JButton();
        jPanel_nuevaClaves = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_claveNueva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton_nuevaClave = new javax.swing.JButton();
        jButton_borrar_campos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_listado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla_info = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jBoton_cerrarListado = new javax.swing.JButton();
        jBoton_mostrarclaves = new javax.swing.JButton();
        jPanel_modifica_pass = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPassModificar = new javax.swing.JPasswordField();
        jPassConfirmarMod = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton_mod_aceptar = new javax.swing.JButton();
        jButton_mod_cancelar = new javax.swing.JButton();
        jPanel_fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jFrame_sesion.setTitle("Iniciar Sesión");
        jFrame_sesion.setAutoRequestFocus(false);
        jFrame_sesion.setMinimumSize(new java.awt.Dimension(820, 510));
        jFrame_sesion.setName("sesion"); // NOI18N
        jFrame_sesion.setUndecorated(true);
        jFrame_sesion.setResizable(false);
        jFrame_sesion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_head_sesion.setBackground(new java.awt.Color(0, 80, 123));
        jPanel_head_sesion.setMaximumSize(new java.awt.Dimension(820, 44));
        jPanel_head_sesion.setMinimumSize(new java.awt.Dimension(820, 44));
        jPanel_head_sesion.setPreferredSize(new java.awt.Dimension(820, 44));

        jBoton_sesion_exit.setBackground(new java.awt.Color(0, 80, 123));
        jBoton_sesion_exit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBoton_sesion_exit.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_sesion_exit.setText("X");
        jBoton_sesion_exit.setToolTipText("");
        jBoton_sesion_exit.setBorder(null);
        jBoton_sesion_exit.setBorderPainted(false);
        jBoton_sesion_exit.setFocusPainted(false);
        jBoton_sesion_exit.setFocusable(false);
        jBoton_sesion_exit.setMaximumSize(new java.awt.Dimension(44, 44));
        jBoton_sesion_exit.setMinimumSize(new java.awt.Dimension(44, 44));
        jBoton_sesion_exit.setPreferredSize(new java.awt.Dimension(44, 44));
        jBoton_sesion_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_sesion_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_sesion_exitMouseExited(evt);
            }
        });
        jBoton_sesion_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_sesion_exitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPanel_head_sesionLayout = new javax.swing.GroupLayout(jPanel_head_sesion);
        jPanel_head_sesion.setLayout(jPanel_head_sesionLayout);
        jPanel_head_sesionLayout.setHorizontalGroup(
            jPanel_head_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_head_sesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 667, Short.MAX_VALUE)
                .addComponent(jBoton_sesion_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_head_sesionLayout.setVerticalGroup(
            jPanel_head_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_head_sesionLayout.createSequentialGroup()
                .addGroup(jPanel_head_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton_sesion_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame_sesion.getContentPane().add(jPanel_head_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 44));

        jPanel_body_sesion.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_body_sesion.setMaximumSize(new java.awt.Dimension(820, 458));
        jPanel_body_sesion.setMinimumSize(new java.awt.Dimension(820, 458));
        jPanel_body_sesion.setPreferredSize(new java.awt.Dimension(820, 458));

        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(375, 446));
        jPanel1.setMinimumSize(new java.awt.Dimension(375, 446));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 446));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 60, 123));
        jLabel5.setText("Nombre de Usuario");

        jTextField_usuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_usuario.setForeground(new java.awt.Color(0, 60, 123));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 60, 123));
        jLabel6.setText("Contraseña");

        jPassword_sesion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPassword_sesion.setForeground(new java.awt.Color(0, 60, 123));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 60, 123));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Iniciar Sesión");

        jBoton_aceptar_sesion.setBackground(new java.awt.Color(0, 80, 123));
        jBoton_aceptar_sesion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBoton_aceptar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_aceptar_sesion.setText("Iniciar Sesión");
        jBoton_aceptar_sesion.setBorderPainted(false);
        jBoton_aceptar_sesion.setFocusPainted(false);
        jBoton_aceptar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_aceptar_sesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_aceptar_sesionMouseExited(evt);
            }
        });
        jBoton_aceptar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_aceptar_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPassword_sesion)
                    .addComponent(jTextField_usuario)
                    .addComponent(jSeparator2)
                    .addComponent(jBoton_aceptar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPassword_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBoton_aceptar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(375, 446));
        jPanel2.setMinimumSize(new java.awt.Dimension(375, 446));
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 446));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 60, 123));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registro");

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 60, 123));
        jLabel9.setText("Nombre de Usuario");

        jTextField_usuario_registro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_usuario_registro.setForeground(new java.awt.Color(0, 60, 123));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 60, 123));
        jLabel10.setText("Contraseña");

        jPasswordField_registro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordField_registro.setForeground(new java.awt.Color(0, 60, 123));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 60, 123));
        jLabel11.setText("Confirma tu contraseña");

        jPasswordField_confirmar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordField_confirmar.setForeground(new java.awt.Color(0, 60, 123));

        jBoton_registro.setBackground(new java.awt.Color(0, 80, 123));
        jBoton_registro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBoton_registro.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_registro.setText("Registrarse");
        jBoton_registro.setBorder(null);
        jBoton_registro.setBorderPainted(false);
        jBoton_registro.setFocusPainted(false);
        jBoton_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_registroMouseExited(evt);
            }
        });
        jBoton_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_usuario_registro)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField_registro)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jPasswordField_confirmar)
                    .addComponent(jSeparator3)
                    .addComponent(jBoton_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField_usuario_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBoton_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_body_sesionLayout = new javax.swing.GroupLayout(jPanel_body_sesion);
        jPanel_body_sesion.setLayout(jPanel_body_sesionLayout);
        jPanel_body_sesionLayout.setHorizontalGroup(
            jPanel_body_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_body_sesionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_body_sesionLayout.setVerticalGroup(
            jPanel_body_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_body_sesionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_body_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jFrame_sesion.getContentPane().add(jPanel_body_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guarda Passwords");
        setBackground(new java.awt.Color(0, 60, 123));
        setMaximumSize(new java.awt.Dimension(830, 560));
        setMinimumSize(new java.awt.Dimension(820, 560));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_head.setBackground(new java.awt.Color(0, 80, 123));
        jPanel_head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guarda Passwords");
        jPanel_head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 3, 180, 40));

        Boton_Minimizar.setBackground(new java.awt.Color(0, 80, 123));
        Boton_Minimizar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Boton_Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Minimizar.setText("-");
        Boton_Minimizar.setToolTipText("Minimizar");
        Boton_Minimizar.setAlignmentY(0.0F);
        Boton_Minimizar.setBorderPainted(false);
        Boton_Minimizar.setFocusPainted(false);
        Boton_Minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Minimizar.setPreferredSize(new java.awt.Dimension(44, 44));
        Boton_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_MinimizarMouseExited(evt);
            }
        });
        jPanel_head.add(Boton_Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 0, -1, -1));

        Boton_Salir.setBackground(new java.awt.Color(0, 80, 123));
        Boton_Salir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setText("X");
        Boton_Salir.setToolTipText("Cerrar");
        Boton_Salir.setBorder(null);
        Boton_Salir.setBorderPainted(false);
        Boton_Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Salir.setPreferredSize(new java.awt.Dimension(44, 44));
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseExited(evt);
            }
        });
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel_head.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, -1));

        getContentPane().add(jPanel_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 44));

        jPanel_sesion.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_sesion.setMaximumSize(new java.awt.Dimension(720, 36));
        jPanel_sesion.setMinimumSize(new java.awt.Dimension(720, 36));

        jLabel_usuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_usuario.setText("Sesión no iniciada");
        jLabel_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_usuario.setMaximumSize(new java.awt.Dimension(255, 36));
        jLabel_usuario.setMinimumSize(new java.awt.Dimension(255, 36));
        jLabel_usuario.setPreferredSize(new java.awt.Dimension(255, 36));

        Boton_Sesion.setBackground(new java.awt.Color(0, 60, 123));
        Boton_Sesion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Boton_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Sesion.setText("Iniciar sesión");
        Boton_Sesion.setBorder(null);
        Boton_Sesion.setBorderPainted(false);
        Boton_Sesion.setFocusPainted(false);
        Boton_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_SesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_SesionMouseExited(evt);
            }
        });
        Boton_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sesionLayout = new javax.swing.GroupLayout(jPanel_sesion);
        jPanel_sesion.setLayout(jPanel_sesionLayout);
        jPanel_sesionLayout.setHorizontalGroup(
            jPanel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_sesionLayout.setVerticalGroup(
            jPanel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Boton_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 44, 720, -1));

        jPanel_menu.setBackground(new java.awt.Color(0, 102, 153));
        jPanel_menu.setLayout(null);

        jBoton_nueva_passw.setBackground(new java.awt.Color(0, 102, 153));
        jBoton_nueva_passw.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jBoton_nueva_passw.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_nueva_passw.setText("+");
        jBoton_nueva_passw.setToolTipText("Añade nueva contraseña");
        jBoton_nueva_passw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 125, 153), 1, true));
        jBoton_nueva_passw.setFocusPainted(false);
        jBoton_nueva_passw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_nueva_passwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_nueva_passwMouseExited(evt);
            }
        });
        jBoton_nueva_passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_nueva_passwActionPerformed(evt);
            }
        });
        jPanel_menu.add(jBoton_nueva_passw);
        jBoton_nueva_passw.setBounds(0, 90, 100, 100);

        jBoton_listar_passw.setBackground(new java.awt.Color(0, 102, 153));
        jBoton_listar_passw.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jBoton_listar_passw.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_listar_passw.setText("Listado");
        jBoton_listar_passw.setToolTipText("Muestra las contraseñas guardadas");
        jBoton_listar_passw.setActionCommand("listado");
        jBoton_listar_passw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 125, 153), 1, true));
        jBoton_listar_passw.setFocusPainted(false);
        jBoton_listar_passw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBoton_listar_passw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_listar_passwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_listar_passwMouseExited(evt);
            }
        });
        jBoton_listar_passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_listar_passwActionPerformed(evt);
            }
        });
        jPanel_menu.add(jBoton_listar_passw);
        jBoton_listar_passw.setBounds(0, 200, 100, 100);

        jBoton_cambiar_passw.setBackground(new java.awt.Color(0, 102, 153));
        jBoton_cambiar_passw.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jBoton_cambiar_passw.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_cambiar_passw.setText("Modificar");
        jBoton_cambiar_passw.setToolTipText("Modifica contraseña usuario");
        jBoton_cambiar_passw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 125, 153), 1, true));
        jBoton_cambiar_passw.setFocusPainted(false);
        jBoton_cambiar_passw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_cambiar_passwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_cambiar_passwMouseExited(evt);
            }
        });
        jBoton_cambiar_passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_cambiar_passwActionPerformed(evt);
            }
        });
        jPanel_menu.add(jBoton_cambiar_passw);
        jBoton_cambiar_passw.setBounds(0, 310, 100, 100);

        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 520));

        jPanel_nuevaClaves.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_nuevaClaves.setMaximumSize(new java.awt.Dimension(720, 480));
        jPanel_nuevaClaves.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel_nuevaClaves.setOpaque(false);
        jPanel_nuevaClaves.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel_nuevaClaves.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Crear nuevas claves");
        jPanel_nuevaClaves.add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 46, 560, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clave nueva:");
        jPanel_nuevaClaves.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 141, -1, -1));

        jTextField_claveNueva.setBackground(new java.awt.Color(0, 60, 123));
        jTextField_claveNueva.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_claveNueva.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_claveNueva.setText("fdfdfdfdfdfdfdfdfffffffffff");
        jTextField_claveNueva.setToolTipText("Clave");
        jTextField_claveNueva.setBorder(null);
        jTextField_claveNueva.setMaximumSize(new java.awt.Dimension(79, 23));
        jTextField_claveNueva.setMinimumSize(new java.awt.Dimension(79, 23));
        jTextField_claveNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_claveNuevaMouseClicked(evt);
            }
        });
        jPanel_nuevaClaves.add(jTextField_claveNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 141, 445, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descripción:");
        jLabel13.setMaximumSize(new java.awt.Dimension(97, 23));
        jLabel13.setMinimumSize(new java.awt.Dimension(97, 23));
        jLabel13.setPreferredSize(new java.awt.Dimension(97, 23));
        jPanel_nuevaClaves.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jTextArea2.setBackground(new java.awt.Color(0, 60, 123));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("Descripción");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(null);
        jTextArea2.setMaximumSize(new java.awt.Dimension(280, 115));
        jTextArea2.setMinimumSize(new java.awt.Dimension(280, 115));
        jScrollPane3.setViewportView(jTextArea2);

        jPanel_nuevaClaves.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 210, 445, -1));

        jButton_nuevaClave.setBackground(new java.awt.Color(0, 102, 153));
        jButton_nuevaClave.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_nuevaClave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_nuevaClave.setText("Aceptar");
        jButton_nuevaClave.setBorder(null);
        jButton_nuevaClave.setBorderPainted(false);
        jButton_nuevaClave.setFocusPainted(false);
        jButton_nuevaClave.setMaximumSize(new java.awt.Dimension(150, 45));
        jButton_nuevaClave.setMinimumSize(new java.awt.Dimension(150, 45));
        jButton_nuevaClave.setPreferredSize(new java.awt.Dimension(150, 45));
        jButton_nuevaClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_nuevaClaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_nuevaClaveMouseExited(evt);
            }
        });
        jButton_nuevaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevaClaveActionPerformed(evt);
            }
        });
        jPanel_nuevaClaves.add(jButton_nuevaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jButton_borrar_campos.setBackground(new java.awt.Color(0, 102, 153));
        jButton_borrar_campos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_borrar_campos.setForeground(new java.awt.Color(255, 255, 255));
        jButton_borrar_campos.setText("Limpiar campos");
        jButton_borrar_campos.setBorder(null);
        jButton_borrar_campos.setBorderPainted(false);
        jButton_borrar_campos.setFocusPainted(false);
        jButton_borrar_campos.setMaximumSize(new java.awt.Dimension(150, 45));
        jButton_borrar_campos.setMinimumSize(new java.awt.Dimension(150, 45));
        jButton_borrar_campos.setPreferredSize(new java.awt.Dimension(150, 45));
        jButton_borrar_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_borrar_camposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_borrar_camposMouseExited(evt);
            }
        });
        jButton_borrar_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_camposActionPerformed(evt);
            }
        });
        jPanel_nuevaClaves.add(jButton_borrar_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 270, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_nuevaClaves.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 170, 445, 10));

        getContentPane().add(jPanel_nuevaClaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jPanel_listado.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_listado.setOpaque(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 55, 55)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTabla_info.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTabla_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Clave", "Descripción", "Contraseña", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabla_info.setAutoscrolls(false);
        jTabla_info.setOpaque(false);
        jTabla_info.setSelectionForeground(new java.awt.Color(0, 0, 204));
        jTabla_info.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTabla_info);
        if (jTabla_info.getColumnModel().getColumnCount() > 0) {
            jTabla_info.getColumnModel().getColumn(0).setResizable(false);
            jTabla_info.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTabla_info.getColumnModel().getColumn(1).setResizable(false);
            jTabla_info.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTabla_info.getColumnModel().getColumn(2).setResizable(false);
            jTabla_info.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTabla_info.getColumnModel().getColumn(3).setResizable(false);
            jTabla_info.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listados de Claves");

        jBoton_cerrarListado.setBackground(new java.awt.Color(0, 102, 153));
        jBoton_cerrarListado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBoton_cerrarListado.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_cerrarListado.setText("Cerrar");
        jBoton_cerrarListado.setBorder(null);
        jBoton_cerrarListado.setBorderPainted(false);
        jBoton_cerrarListado.setFocusPainted(false);
        jBoton_cerrarListado.setMaximumSize(new java.awt.Dimension(150, 45));
        jBoton_cerrarListado.setMinimumSize(new java.awt.Dimension(150, 45));
        jBoton_cerrarListado.setPreferredSize(new java.awt.Dimension(150, 45));
        jBoton_cerrarListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_cerrarListadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_cerrarListadoMouseExited(evt);
            }
        });
        jBoton_cerrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_cerrarListadoActionPerformed(evt);
            }
        });

        jBoton_mostrarclaves.setBackground(new java.awt.Color(0, 102, 153));
        jBoton_mostrarclaves.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBoton_mostrarclaves.setForeground(new java.awt.Color(255, 255, 255));
        jBoton_mostrarclaves.setText("Mostrar Claves");
        jBoton_mostrarclaves.setToolTipText("");
        jBoton_mostrarclaves.setBorder(null);
        jBoton_mostrarclaves.setBorderPainted(false);
        jBoton_mostrarclaves.setFocusPainted(false);
        jBoton_mostrarclaves.setMaximumSize(new java.awt.Dimension(150, 45));
        jBoton_mostrarclaves.setMinimumSize(new java.awt.Dimension(150, 45));
        jBoton_mostrarclaves.setPreferredSize(new java.awt.Dimension(150, 45));
        jBoton_mostrarclaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBoton_mostrarclavesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBoton_mostrarclavesMouseExited(evt);
            }
        });
        jBoton_mostrarclaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_mostrarclavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listadoLayout = new javax.swing.GroupLayout(jPanel_listado);
        jPanel_listado.setLayout(jPanel_listadoLayout);
        jPanel_listadoLayout.setHorizontalGroup(
            jPanel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_listadoLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jBoton_cerrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jBoton_mostrarclaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_listadoLayout.setVerticalGroup(
            jPanel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton_cerrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton_mostrarclaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 720, -1));

        jPanel_modifica_pass.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_modifica_pass.setMaximumSize(new java.awt.Dimension(720, 480));
        jPanel_modifica_pass.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel_modifica_pass.setOpaque(false);
        jPanel_modifica_pass.setPreferredSize(new java.awt.Dimension(720, 480));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Modificar clave de usuario");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nueva contraseña:");
        jLabel15.setMaximumSize(new java.awt.Dimension(169, 23));
        jLabel15.setMinimumSize(new java.awt.Dimension(169, 23));
        jLabel15.setPreferredSize(new java.awt.Dimension(169, 23));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Confirmar contraseña:");

        jPassModificar.setBackground(new java.awt.Color(0, 60, 123));
        jPassModificar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPassModificar.setForeground(new java.awt.Color(255, 255, 255));
        jPassModificar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPassModificar.setBorder(null);
        jPassModificar.setMaximumSize(new java.awt.Dimension(139, 27));
        jPassModificar.setMinimumSize(new java.awt.Dimension(139, 27));

        jPassConfirmarMod.setBackground(new java.awt.Color(0, 60, 123));
        jPassConfirmarMod.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPassConfirmarMod.setForeground(new java.awt.Color(255, 255, 255));
        jPassConfirmarMod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPassConfirmarMod.setBorder(null);
        jPassConfirmarMod.setMaximumSize(new java.awt.Dimension(139, 27));
        jPassConfirmarMod.setMinimumSize(new java.awt.Dimension(139, 27));
        jPassConfirmarMod.setPreferredSize(new java.awt.Dimension(139, 27));

        jButton_mod_aceptar.setBackground(new java.awt.Color(0, 102, 153));
        jButton_mod_aceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_mod_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mod_aceptar.setText("Aceptar");
        jButton_mod_aceptar.setToolTipText("");
        jButton_mod_aceptar.setBorder(null);
        jButton_mod_aceptar.setBorderPainted(false);
        jButton_mod_aceptar.setFocusable(false);
        jButton_mod_aceptar.setMaximumSize(new java.awt.Dimension(150, 45));
        jButton_mod_aceptar.setMinimumSize(new java.awt.Dimension(150, 45));
        jButton_mod_aceptar.setPreferredSize(new java.awt.Dimension(150, 45));
        jButton_mod_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_mod_aceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_mod_aceptarMouseExited(evt);
            }
        });
        jButton_mod_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mod_aceptarActionPerformed(evt);
            }
        });

        jButton_mod_cancelar.setBackground(new java.awt.Color(0, 102, 153));
        jButton_mod_cancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_mod_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mod_cancelar.setText("Cancelar");
        jButton_mod_cancelar.setBorder(null);
        jButton_mod_cancelar.setFocusPainted(false);
        jButton_mod_cancelar.setMaximumSize(new java.awt.Dimension(150, 45));
        jButton_mod_cancelar.setMinimumSize(new java.awt.Dimension(150, 45));
        jButton_mod_cancelar.setPreferredSize(new java.awt.Dimension(150, 45));
        jButton_mod_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_mod_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_mod_cancelarMouseExited(evt);
            }
        });
        jButton_mod_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mod_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_modifica_passLayout = new javax.swing.GroupLayout(jPanel_modifica_pass);
        jPanel_modifica_pass.setLayout(jPanel_modifica_passLayout);
        jPanel_modifica_passLayout.setHorizontalGroup(
            jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel14))
                    .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jPassModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPassConfirmarMod, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_modifica_passLayout.createSequentialGroup()
                                .addComponent(jButton_mod_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton_mod_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel_modifica_passLayout.setVerticalGroup(
            jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modifica_passLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel14)
                .addGap(60, 60, 60)
                .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPassConfirmarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel_modifica_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_mod_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_mod_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_modifica_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jPanel_fondo.setBackground(new java.awt.Color(0, 60, 123));
        jPanel_fondo.setMaximumSize(new java.awt.Dimension(720, 480));
        jPanel_fondo.setMinimumSize(new java.awt.Dimension(720, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondo.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(720, 480));
        jLabel2.setMinimumSize(new java.awt.Dimension(720, 480));
        jLabel2.setPreferredSize(new java.awt.Dimension(720, 480));

        javax.swing.GroupLayout jPanel_fondoLayout = new javax.swing.GroupLayout(jPanel_fondo);
        jPanel_fondo.setLayout(jPanel_fondoLayout);
        jPanel_fondoLayout.setHorizontalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_fondoLayout.setVerticalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseExited
        this.Boton_Salir.setBackground(new Color(0, 80, 123));
        this.Boton_Salir.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_SalirMouseExited

    private void Boton_SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseEntered
        this.Boton_Salir.setBackground(new Color(255, 0, 0));
        this.Boton_Salir.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_SalirMouseEntered

    private void Boton_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_MinimizarMouseEntered
        this.Boton_Minimizar.setBackground(new Color(0, 30, 123));
        this.Boton_Minimizar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_MinimizarMouseEntered

    private void Boton_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_MinimizarMouseExited
        this.Boton_Minimizar.setBackground(new Color(0, 80, 123));
        this.Boton_Minimizar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_MinimizarMouseExited

    private void Boton_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_Boton_MinimizarMouseClicked

    private void Boton_SesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SesionMouseEntered
        this.Boton_Sesion.setBackground(new Color(0, 225, 255));
        this.Boton_Sesion.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_SesionMouseEntered

    private void Boton_SesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SesionMouseExited
        this.Boton_Sesion.setBackground(new Color(0, 60, 123));
        this.Boton_Sesion.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Boton_SesionMouseExited

    private void jBoton_nueva_passwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_nueva_passwMouseEntered
        this.jBoton_nueva_passw.setBackground(new Color(0, 60, 150));
        this.jBoton_nueva_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_nueva_passwMouseEntered

    private void jBoton_nueva_passwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_nueva_passwMouseExited
        this.jBoton_nueva_passw.setBackground(new Color(0, 102, 153));
        this.jBoton_nueva_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_nueva_passwMouseExited

    private void jBoton_listar_passwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_listar_passwMouseEntered
        this.jBoton_listar_passw.setBackground(new Color(0, 60, 150));
        this.jBoton_listar_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_listar_passwMouseEntered

    private void jBoton_listar_passwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_listar_passwMouseExited
        this.jBoton_listar_passw.setBackground(new Color(0, 102, 153));
        this.jBoton_listar_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_listar_passwMouseExited

    private void jBoton_cambiar_passwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_cambiar_passwMouseEntered
        this.jBoton_cambiar_passw.setBackground(new Color(0, 60, 150));
        this.jBoton_cambiar_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_cambiar_passwMouseEntered

    private void jBoton_cambiar_passwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_cambiar_passwMouseExited
        this.jBoton_cambiar_passw.setBackground(new Color(0, 102, 153));
        this.jBoton_cambiar_passw.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_cambiar_passwMouseExited

    private void Boton_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SesionActionPerformed

        this.reset_campos();

        if (this.isSesion == false) {
            if (this.gestorUsuario.comprobarUsuario() == true) { //Si existe algun usuario
                this.jTextField_usuario.setText(this.usuario.getNombreUsuario());
                //this.jPassword_sesion.setText(this.usuario.getPassword());
                this.jBoton_registro.setEnabled(false);
                this.jBoton_aceptar_sesion.setEnabled(true);
            } else {
                this.jBoton_aceptar_sesion.setEnabled(false);
                this.jBoton_registro.setEnabled(true);
            }

            this.dispose();
            this.Boton_Sesion.setText("Cerrar Sesión");
            this.jFrame_sesion.setLocationRelativeTo(this);
            this.jFrame_sesion.setVisible(true);
            this.isSesion = true;
        } else {
            this.Boton_Sesion.setText("Iniciar Sesión");
            this.jLabel_usuario.setText("Sesión no iniciada");
            this.jPanel_nuevaClaves.setVisible(false);
            this.jPanel_listado.setVisible(false);
            this.jPanel_modifica_pass.setVisible(false);
            this.isSesion = false;
        }


    }//GEN-LAST:event_Boton_SesionActionPerformed

    private void jBoton_sesion_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_sesion_exitMouseEntered
        this.jBoton_sesion_exit.setBackground(new Color(255, 0, 0));
        this.jBoton_sesion_exit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_sesion_exitMouseEntered

    private void jBoton_sesion_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_sesion_exitMouseExited
        this.jBoton_sesion_exit.setBackground(new Color(0, 80, 123));
        this.jBoton_sesion_exit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBoton_sesion_exitMouseExited

    private void jBoton_sesion_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_sesion_exitActionPerformed
        this.jFrame_sesion.setVisible(false);
        this.Boton_Sesion.setText("Iniciar Sesión");
        this.jLabel_usuario.setText("Sesión no iniciada");
        this.isSesion = false;
        this.setVisible(true);
    }//GEN-LAST:event_jBoton_sesion_exitActionPerformed

    private void jBoton_aceptar_sesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_aceptar_sesionMouseEntered
        this.jBoton_aceptar_sesion.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jBoton_aceptar_sesionMouseEntered

    private void jBoton_aceptar_sesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_aceptar_sesionMouseExited
        this.jBoton_aceptar_sesion.setBackground(new Color(0, 80, 123));
    }//GEN-LAST:event_jBoton_aceptar_sesionMouseExited

    private void jBoton_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_registroMouseEntered
        this.jBoton_registro.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jBoton_registroMouseEntered

    private void jBoton_registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_registroMouseExited
        this.jBoton_registro.setBackground(new Color(0, 80, 123));
    }//GEN-LAST:event_jBoton_registroMouseExited

    private void jBoton_nueva_passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_nueva_passwActionPerformed
        if (this.isSesion == false) { //Si no ha iniciado sesion
            men.showMessageDialog(null, "Debes iniciar sesión", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            this.jPanel_listado.setVisible(false);  //Ocultas las ventanas
            this.jPanel_modifica_pass.setVisible(false);
            if (this.jPanel_nuevaClaves.isVisible() == false) {
                this.jPanel_nuevaClaves.setVisible(true);  //Activa la ventana para añadir claves
            } else {
                this.jPanel_nuevaClaves.setVisible(false);
                this.jButton_nuevaClave.setLocation(240, 270);  //Recolocas los botones para ocultarlo
                this.jButton_borrar_campos.setLocation(445, 270);
            }
        }
    }//GEN-LAST:event_jBoton_nueva_passwActionPerformed

    private void jBoton_listar_passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_listar_passwActionPerformed
        List <Object []> listar;
        DefaultTableModel dataModel = (DefaultTableModel) this.jTabla_info.getModel();
        Object temp[] = new Object[4]; //0 IdClave, 1 Descripcion, 2 Clave, 3 Nombre Usuario
 
        
        if (this.isSesion == false) { //Si no ha iniciado sesion
            men.showMessageDialog(null, "Debes iniciar sesión", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            this.Borrar_tabla();

            this.jPanel_nuevaClaves.setVisible(false); //Oculta la ventana
            this.jPanel_modifica_pass.setVisible(false);
            this.jButton_nuevaClave.setLocation(240, 270);
            this.jButton_borrar_campos.setLocation(445, 270);
            if (this.jPanel_listado.isVisible() == false) {
                
                listar = this.gestorClaves.listarClaves();
                if (listar != null) {
                    this.jBoton_mostrarclaves.setEnabled(true);
                    this.jBoton_mostrarclaves.setText("Mostrar Claves");
                    for (int i = 0; i < listar.size(); i++) {
                        temp = listar.get(i);
                        dataModel.addRow(temp);
                        this.jTabla_info.setModel(dataModel);
                    }
                }
                else {
                    this.jBoton_mostrarclaves.setEnabled(false);
                }
                this.jPanel_listado.setVisible(true); //Activa la ventana para el listado de claves
            } else {
                this.jPanel_listado.setVisible(false);
                this.Borrar_tabla();
            }
        }
    }//GEN-LAST:event_jBoton_listar_passwActionPerformed

    private void jBoton_cambiar_passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_cambiar_passwActionPerformed
        if (this.isSesion == false) { //Si no ha iniciado sesion
            men.showMessageDialog(null, "Debes iniciar sesión", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            this.jPanel_nuevaClaves.setVisible(false); //Oculta la ventana
            this.jPanel_listado.setVisible(false);
            this.jButton_nuevaClave.setLocation(240, 270);
            this.jButton_borrar_campos.setLocation(445, 270);
            if (this.jPanel_modifica_pass.isVisible() == false) {
                this.jPanel_modifica_pass.setVisible(true); //Activa la ventana para el listado de claves
            } else {
                this.jPanel_modifica_pass.setVisible(false);
            }
        }
    }//GEN-LAST:event_jBoton_cambiar_passwActionPerformed

    private void jButton_nuevaClaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_nuevaClaveMouseEntered
        this.jButton_nuevaClave.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jButton_nuevaClaveMouseEntered

    private void jButton_nuevaClaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_nuevaClaveMouseExited
        this.jButton_nuevaClave.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jButton_nuevaClaveMouseExited

    private void jButton_borrar_camposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_borrar_camposMouseEntered
        this.jButton_borrar_campos.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jButton_borrar_camposMouseEntered

    private void jButton_borrar_camposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_borrar_camposMouseExited
        this.jButton_borrar_campos.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jButton_borrar_camposMouseExited

    private void jTextField_claveNuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_claveNuevaMouseClicked
        int delay = 2;

        this.animar = new Timer(delay, this.ejecutarAnimacion);

        this.animar.start();

    }//GEN-LAST:event_jTextField_claveNuevaMouseClicked

    private void jButton_borrar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrar_camposActionPerformed
        this.reset_campos();
    }//GEN-LAST:event_jButton_borrar_camposActionPerformed

    private void jButton_mod_aceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mod_aceptarMouseEntered
        this.jButton_mod_aceptar.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jButton_mod_aceptarMouseEntered

    private void jButton_mod_aceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mod_aceptarMouseExited
        this.jButton_mod_aceptar.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jButton_mod_aceptarMouseExited

    private void jButton_mod_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mod_cancelarMouseEntered
        this.jButton_mod_cancelar.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jButton_mod_cancelarMouseEntered

    private void jButton_mod_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mod_cancelarMouseExited
        this.jButton_mod_cancelar.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_jButton_mod_cancelarMouseExited

    private void jButton_mod_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mod_cancelarActionPerformed
        this.men.showMessageDialog(null, "Clave no modificada", "Modificacion Clave", JOptionPane.INFORMATION_MESSAGE);
        this.jPanel_modifica_pass.setVisible(false);
        this.reset_campos();
    }//GEN-LAST:event_jButton_mod_cancelarActionPerformed

    private void jBoton_aceptar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_aceptar_sesionActionPerformed
        String cifrado;
        
        
        if (this.gestorUsuario.confirmaUsuario(this.jTextField_usuario.getText()) == false) {
            this.men.showMessageDialog(null, "El usuario no existe", "Nombre Usuario", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                cifrado = this.cifrar.CifrarClaveUsuario(this.jPassword_sesion.getText());
                this.usuario.setPassword(cifrado.substring(0, 16));
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }            
                        
            if (this.gestorUsuario.confirmaPassword(this.usuario.getPassword()) == false) {
                this.men.showMessageDialog(null, "Contraseña incorrecta", "Contraseña", JOptionPane.WARNING_MESSAGE);
            } else {
                this.Boton_Sesion.setText("Cerrar Sesión");
                this.jLabel_usuario.setText("Sesión Iniciada por: "+this.usuario.getNombreUsuario());
                this.Boton_Sesion.setBackground(new Color(0,60,123));
                this.isSesion = true;
                this.jFrame_sesion.setVisible(false);
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_jBoton_aceptar_sesionActionPerformed

    private void jBoton_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_registroActionPerformed
        String cifrado;
        
        if (this.jTextField_usuario_registro.getText().compareTo("") == 0) {
            this.men.showMessageDialog(null, "Campo Obligatorio", "Nombre Usuario", JOptionPane.WARNING_MESSAGE);
        } else {
            if (this.jPasswordField_registro.getText().compareTo(this.jPasswordField_confirmar.getText()) != 0) {
                this.men.showMessageDialog(null, "La contraseña es distinta", "Contraseña", JOptionPane.WARNING_MESSAGE);
            } else {
                this.usuario = new Usuarios();
                this.usuario.setNombreUsuario(this.jTextField_usuario_registro.getText());
                
                try {
                    cifrado = this.cifrar.CifrarClaveUsuario(this.jPasswordField_registro.getText());
                    this.usuario.setPassword(cifrado.substring(0, 16));
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }                 
                
                if (this.gestorUsuario.guardaUsuario(usuario) == true) {
                    this.men.showMessageDialog(null, "Usuario registrado correctamente", "Usuario", JOptionPane.INFORMATION_MESSAGE);
                    this.Boton_Sesion.setText("Cerrar Sesión");
                    this.jLabel_usuario.setText("Sesión Iniciada por: "+this.usuario.getNombreUsuario());
                    this.Boton_Sesion.setBackground(new Color(0,60,123));
                    this.isSesion = true;
                    this.jFrame_sesion.setVisible(false);
                    this.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jBoton_registroActionPerformed

    private void jButton_mod_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mod_aceptarActionPerformed
        String cifrado;
        
        if (this.jPassModificar.getText().compareTo("") == 0) {
            this.men.showMessageDialog(null, "Campo Obligatorio", "Contraseña", JOptionPane.WARNING_MESSAGE);
        }
        else {   
            if (this.jPassModificar.getText().compareTo(this.jPassConfirmarMod.getText()) != 0) {
                this.men.showMessageDialog(null, "La contraseña es distinta", "Contraseña", JOptionPane.WARNING_MESSAGE);
            }
            else {
                //this.usuario.setPassword(this.jPassModificar.getText());

                try {
                    cifrado = this.cifrar.CifrarClaveUsuario(this.jPassModificar.getText());
                    this.usuario.setPassword(cifrado.substring(0, 16));
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }                 
                                
                if (this.gestorUsuario.modificaPassword(usuario) == true){
                    this.men.showMessageDialog(null, "La contraseña ha sido modificada correctamente", "Contraseña", JOptionPane.INFORMATION_MESSAGE);
                    this.jPanel_modifica_pass.setVisible(false);
                }
            }
        }
        
    }//GEN-LAST:event_jButton_mod_aceptarActionPerformed

    private void jButton_nuevaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevaClaveActionPerformed
        String cifrado;
        if (this.jTextField_claveNueva.getText().compareTo("") == 0) {
            men.showMessageDialog(null, "Campo Obligatorio", "Contraseña", JOptionPane.WARNING_MESSAGE);
        } else {
            if (this.jTextArea2.getText().compareTo("") == 0) {
                men.showMessageDialog(null, "Campo Obligatorio", "Descripción", JOptionPane.WARNING_MESSAGE);
            } else {
                this.misclaves = new Misclaves();

                cifrado = this.cifrar.CifrarClave(this.jTextField_claveNueva.getText());
                this.misclaves.setClave(cifrado);

//                this.misclaves.setClave(this.jTextField_claveNueva.getText());
                this.misclaves.setDescripcion(this.jTextArea2.getText());
                this.misclaves.setNombreUsuario(this.usuario.getNombreUsuario());

                if (this.gestorClaves.nuevaClaves(misclaves) == true) {
                    men.showMessageDialog(null, "Claves guardadas correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                    this.reset_campos();
                }
            }
        }
    }//GEN-LAST:event_jButton_nuevaClaveActionPerformed

    private void jBoton_cerrarListadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_cerrarListadoMouseEntered
        this.jBoton_cerrarListado.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jBoton_cerrarListadoMouseEntered

    private void jBoton_cerrarListadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_cerrarListadoMouseExited
        this.jBoton_cerrarListado.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_jBoton_cerrarListadoMouseExited

    private void jBoton_cerrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_cerrarListadoActionPerformed
        this.jPanel_listado.setVisible(false);
    }//GEN-LAST:event_jBoton_cerrarListadoActionPerformed

    private void jBoton_mostrarclavesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_mostrarclavesMouseEntered
        this.jBoton_mostrarclaves.setBackground(new Color(0, 185, 175));
    }//GEN-LAST:event_jBoton_mostrarclavesMouseEntered

    private void jBoton_mostrarclavesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_mostrarclavesMouseExited
        this.jBoton_mostrarclaves.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_jBoton_mostrarclavesMouseExited

    private void jBoton_mostrarclavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_mostrarclavesActionPerformed
        String cifrado, descifrado;
        if (this.jBoton_mostrarclaves.getText().compareTo("Mostrar Claves") == 0){
            this.jBoton_mostrarclaves.setText("Ocultar Claves");
            
            for(int i= 0; i < this.jTabla_info.getRowCount(); i++){
                cifrado= this.jTabla_info.getValueAt(i, 2).toString();
                
                descifrado= this.cifrar.DesCifrarClave(cifrado);
                
                this.jTabla_info.setValueAt(descifrado, i, 2);
            }  
        }
        else {
            this.jBoton_mostrarclaves.setText("Mostrar Claves");
            
            for(int i= 0; i < this.jTabla_info.getRowCount(); i++){
                descifrado= this.jTabla_info.getValueAt(i, 2).toString();
                
                cifrado= this.cifrar.CifrarClave(descifrado);
                
                this.jTabla_info.setValueAt(cifrado, i, 2);
            }            
        }
    }//GEN-LAST:event_jBoton_mostrarclavesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    private void reset_campos() {
        this.jTextField_usuario.setText("");
        this.jTextField_usuario_registro.setText("");
        this.jPassword_sesion.setText("");
        this.jPasswordField_registro.setText("");
        this.jPasswordField_confirmar.setText("");
        this.jTextField_claveNueva.setText("");
        this.jTextArea2.setText("");
        this.jTextField_claveNueva.setText("");
        this.jTextArea2.setText("");
        this.jPassModificar.setText("");
        this.jPassConfirmarMod.setText("");
    }

    private void Borrar_tabla() {
        DefaultTableModel temp = (DefaultTableModel) this.jTabla_info.getModel();
        int fila = this.jTabla_info.getRowCount();

        try {
            for (int i = fila; i > 0; i--) {
                temp.removeRow(0);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            men.showMessageDialog(null, "Error a eliminar fila en la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Minimizar;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_Sesion;
    private javax.swing.JButton jBoton_aceptar_sesion;
    private javax.swing.JButton jBoton_cambiar_passw;
    private javax.swing.JButton jBoton_cerrarListado;
    private javax.swing.JButton jBoton_listar_passw;
    private javax.swing.JButton jBoton_mostrarclaves;
    private javax.swing.JButton jBoton_nueva_passw;
    private javax.swing.JButton jBoton_registro;
    private javax.swing.JButton jBoton_sesion_exit;
    private javax.swing.JButton jButton_borrar_campos;
    private javax.swing.JButton jButton_mod_aceptar;
    private javax.swing.JButton jButton_mod_cancelar;
    private javax.swing.JButton jButton_nuevaClave;
    private javax.swing.JFrame jFrame_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_body_sesion;
    private javax.swing.JPanel jPanel_fondo;
    private javax.swing.JPanel jPanel_head;
    private javax.swing.JPanel jPanel_head_sesion;
    private javax.swing.JPanel jPanel_listado;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_modifica_pass;
    private javax.swing.JPanel jPanel_nuevaClaves;
    private javax.swing.JPanel jPanel_sesion;
    private javax.swing.JPasswordField jPassConfirmarMod;
    private javax.swing.JPasswordField jPassModificar;
    private javax.swing.JPasswordField jPasswordField_confirmar;
    private javax.swing.JPasswordField jPasswordField_registro;
    private javax.swing.JPasswordField jPassword_sesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTabla_info;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField_claveNueva;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JTextField jTextField_usuario_registro;
    // End of variables declaration//GEN-END:variables

}
