package com.mycompany.guardatupassword;
// Generated 20-may-2017 11:16:05 by Hibernate Tools 4.3.1



/**
 * Misclaves generated by hbm2java
 */
public class Misclaves  implements java.io.Serializable {


     private Integer idClaves;
     private String descripcion;
     private String clave;
     private String nombreUsuario;

    public Misclaves() {
    }

    public Misclaves(String descripcion, String clave, String nombreUsuario) {
       this.descripcion = descripcion;
       this.clave = clave;
       this.nombreUsuario = nombreUsuario;
    }
   
    public Integer getIdClaves() {
        return this.idClaves;
    }
    
    public void setIdClaves(Integer idClaves) {
        this.idClaves = idClaves;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }




}


